version: '3.7'
services:
    node-app:
      container_name: node-app-mongo
      image: world
      restart: always
      volumes: 
        - .:/usr/src/app/.
      ports:
        - '5002:5000'
    #   depends_on: 
    #     - mongodb
    #   links: 
    #     - mongodb
    # mongodb:
    #   container_name: mongodb_one
    #   image: mongo:rc
    #   # volumes: 
    #   #   - /d/mongo/db:/data/db
    #   ports: 
    #     - '27017:27017'